import json
from typing import List, Dict, Any
from app.core.config import settings

class LLMProvider:
    """Provider-agnostic LLM interface with robust deterministic fallbacks."""

    @staticmethod
    def generate_assessment_questions(
        target_role: str,
        degree: str,
        skills: List[str],
        count: int
    ) -> List[Dict[str, Any]]:
        # In mock or fallback mode, generate tailored questions based on role
        questions = []
        is_tech = any(keyword in target_role.lower() for keyword in ["engineer", "developer", "sde", "code"])

        if is_tech:
            questions.append({
                "category": "technical",
                "topic": "Algorithms",
                "subTopic": "Sorting & Searching",
                "questionType": "single_choice",
                "difficulty": "medium",
                "prompt": f"Given an unsorted array of n elements, what is the optimal worst-case time complexity for comparison-based sorting for a {target_role} system?",
                "options": [
                    {"optionId": "A", "text": "O(n)"},
                    {"optionId": "B", "text": "O(n log n)"},
                    {"optionId": "C", "text": "O(n^2)"},
                    {"optionId": "D", "text": "O(log n)"}
                ],
                "correctOptionIds": ["B"],
                "explanation": "Any comparison-based sorting algorithm requires at least Omega(n log n) comparisons in the worst case (e.g. Merge Sort, Heap Sort).",
                "suggestedActionOnFailure": "Review comparison-based lower bounds and sorting complexities."
            })
            questions.append({
                "category": "technical",
                "topic": "System Design",
                "subTopic": "Caching",
                "questionType": "single_choice",
                "difficulty": "medium",
                "prompt": "Which caching eviction policy removes the item that has not been accessed for the longest period of time?",
                "options": [
                    {"optionId": "A", "text": "FIFO (First In First Out)"},
                    {"optionId": "B", "text": "LFU (Least Frequently Used)"},
                    {"optionId": "C", "text": "LRU (Least Recently Used)"},
                    {"optionId": "D", "text": "Random Replacement"}
                ],
                "correctOptionIds": ["C"],
                "explanation": "LRU discards the least recently used items first by tracking timestamp or access order.",
                "suggestedActionOnFailure": "Implement an LRU cache using a Doubly Linked List and Hash Map."
            })
        else:
            questions.append({
                "category": "domain",
                "topic": "Market Analysis",
                "subTopic": "KPIs",
                "questionType": "single_choice",
                "difficulty": "medium",
                "prompt": f"In {target_role} strategy, what is Customer Acquisition Cost (CAC)?",
                "options": [
                    {"optionId": "A", "text": "Total cost of sales and marketing divided by number of new customers acquired"},
                    {"optionId": "B", "text": "The annual profit generated by one subscriber"},
                    {"optionId": "C", "text": "The operational expenditure required to build the core product"},
                    {"optionId": "D", "text": "Net revenue retention rate minus churn"}
                ],
                "correctOptionIds": ["A"],
                "explanation": "CAC represents the total cost associated with convincing a customer to purchase a product/service.",
                "suggestedActionOnFailure": "Review core business unit metrics (CAC, LTV, Churn)."
            })

        # Add shared aptitude & communication questions
        questions.append({
            "category": "aptitude",
            "topic": "Quantitative Reasoning",
            "subTopic": "Ratios & Proportions",
            "questionType": "single_choice",
            "difficulty": "medium",
            "prompt": "If a car travels 240 kilometers in 3 hours, what is its average speed in meters per second?",
            "options": [
                {"optionId": "A", "text": "20.2 m/s"},
                {"optionId": "B", "text": "22.2 m/s"},
                {"optionId": "C", "text": "25.0 m/s"},
                {"optionId": "D", "text": "80.0 m/s"}
            ],
            "correctOptionIds": ["B"],
            "explanation": "Speed = 240 km / 3 h = 80 km/h. Convert to m/s: 80 * (5/18) = 22.22 m/s.",
            "suggestedActionOnFailure": "Review metric speed unit conversion formulas."
        })
        questions.append({
            "category": "communication",
            "topic": "Workplace Communication",
            "subTopic": "Conflict Resolution",
            "questionType": "single_choice",
            "difficulty": "medium",
            "prompt": "During a cross-functional alignment meeting, a teammate strongly disagrees with your technical proposal. How should you respond?",
            "options": [
                {"optionId": "A", "text": "Dismiss their concerns immediately to save meeting time"},
                {"optionId": "B", "text": "Acknowledge their perspective, ask clarifying questions to understand root constraints, and evaluate objectively against metrics"},
                {"optionId": "C", "text": "Escalate to the executive team without discussing further"},
                {"optionId": "D", "text": "Concede immediately to avoid conflict"}
            ],
            "correctOptionIds": ["B"],
            "explanation": "Constructive inquiry and data-backed trade-off analysis defuse conflict and yield higher team alignment.",
            "suggestedActionOnFailure": "Study collaborative negotiation and active listening principles."
        })

        return questions[:count]

    @staticmethod
    def analyze_weakness_patterns(weaknesses: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        insights = []
        for w in weaknesses:
            topic = w.get("topic", "General")
            acc = w.get("accuracyRate", 0.0)
            insights.append({
                "category": w.get("category", "technical"),
                "topic": topic,
                "severity": "critical" if acc < 0.3 else "high" if acc < 0.5 else "medium",
                "plainLanguageInsight": f"Your placement assessment performance shows systematic vulnerability in {topic} (accuracy: {int(acc * 100)}%).",
                "concreteRecommendation": f"Dedicate 25 minutes of your daily practice plan to targeted drills in {topic}."
            })
        return insights
